"""
A simple RULE-BASED chatbot: it checks the patient's message against
known keyword patterns, in priority order, and returns the first
matching response. This is intentionally simple and predictable —
real symptom-checker bots favor this over a free-form LLM for safety
(you don't want a model improvising medical advice).

To upgrade this later to a real LLM: replace get_bot_reply()'s body
with a call to an LLM API (e.g. Anthropic's), passing the patient's
message plus a system prompt instructing it to be cautious and always
recommend seeing a real doctor. Everything else (the router, schemas)
would stay the same.
"""

# Each entry: (keywords to look for, specialization to suggest, reply text)
SYMPTOM_RULES = [
    (
        ["chest pain", "heart", "palpitation", "short of breath"],
        "Cardiology",
        "Chest pain or heart-related symptoms can be serious. "
        "I'd recommend booking an appointment with a Cardiologist soon.",
    ),
    (
        ["fever", "cold", "cough", "flu", "sore throat"],
        "General Physician",
        "Those sound like general symptoms — a General Physician "
        "would be a good place to start.",
    ),
    (
        ["skin", "rash", "itching", "acne"],
        "Dermatology",
        "Skin-related concerns are best handled by a Dermatologist.",
    ),
    (
        ["bone", "fracture", "joint", "back pain", "knee"],
        "Orthopedics",
        "For bone or joint issues, an Orthopedic specialist would be the right fit.",
    ),
    (
        ["anxious", "anxiety", "stressed", "depression", "sad", "mental health"],
        "Psychiatry",
        "Thank you for sharing that. A Psychiatrist or counselor would be "
        "able to help — please also reach out to someone you trust.",
    ),
    (
        ["eye", "vision", "blurry"],
        "Ophthalmology",
        "For eye or vision concerns, an Ophthalmologist can help.",
    ),
    (
        ["child", "baby", "infant"],
        "Pediatrics",
        "For a child's health concerns, a Pediatrician is the right specialist.",
    ),
]

# Non-symptom FAQ-style patterns, checked before symptom rules.
FAQ_RULES = [
    (
        ["hello", "hi", "hey"],
        "Hi! I can help point you to the right specialist based on your "
        "symptoms, or answer questions about booking appointments. "
        "What's going on?",
    ),
    (
        ["book", "appointment", "schedule"],
        "To book an appointment: browse doctors under 'Doctors', pick one, "
        "then use the appointment booking option with your preferred time.",
    ),
    (
        ["risk score", "prediction", "risk assessment"],
        "Your risk score is generated by our AI model from your clinical "
        "data, and shows the top factors that influenced it — you can view "
        "this on any medical record that's had a prediction run on it.",
    ),
]


def get_bot_reply(message: str) -> dict:
    """
    Checks the message against FAQ rules first, then symptom rules.
    Returns a dict with the reply text and (if matched via symptoms)
    a suggested specialization.
    """
    lowered = message.lower()

    for keywords, reply in FAQ_RULES:
        if any(keyword in lowered for keyword in keywords):
            return {"reply": reply, "suggested_specialization": None}

    for keywords, specialization, reply in SYMPTOM_RULES:
        if any(keyword in lowered for keyword in keywords):
            return {"reply": reply, "suggested_specialization": specialization}

    return {
        "reply": "I'm not sure I understood that. Could you describe your "
        "symptoms, or ask about booking an appointment?",
        "suggested_specialization": None,
    }
